"""alargar deploys.origem para 200

Revision ID: 417902adb707
Revises: 9c311b4bb27f
Create Date: 2026-07-17 16:29:25.796661

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "417902adb707"
down_revision: str | None = "9c311b4bb27f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deploys",
        "origem",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deploys",
        "origem",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
