"""empresa_config

Revision ID: 7b1cc57111e9
Revises: d2f6b8c4a1e7
Create Date: 2026-07-07 08:57:39.538494

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b1cc57111e9"
down_revision: str | None = "d2f6b8c4a1e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("razao_social", sa.String(length=160), nullable=True),
        sa.Column("nome_fantasia", sa.String(length=160), nullable=True),
        sa.Column("cnpj", sa.String(length=20), nullable=True),
        sa.Column("inscricao_estadual", sa.String(length=20), nullable=True),
        sa.Column("telefone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=180), nullable=True),
        sa.Column("endereco", sa.Text(), nullable=True),
        sa.Column("observacao_cupom", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("empresa_config")
    # ### end Alembic commands ###
