"""deploys e cache do status do CI

Revision ID: 9c311b4bb27f
Revises: e8c1d2a3b4f5
Create Date: 2026-07-16 14:31:13.758866

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c311b4bb27f"
down_revision: str | None = "e8c1d2a3b4f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ci_status_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("consultado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("erro", sa.String(length=200), nullable=True),
        sa.Column("runs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("release_tag", sa.String(length=60), nullable=True),
        sa.Column("release_url", sa.String(length=300), nullable=True),
        sa.Column("release_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proxima_tentativa_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("falhas_seguidas", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deploys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acao", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("versao_anterior", sa.String(length=60), nullable=True),
        sa.Column("versao_nova", sa.String(length=60), nullable=False),
        sa.Column("imagem_digest", sa.String(length=120), nullable=True),
        sa.Column("origem", sa.String(length=20), nullable=True),
        sa.Column("alembic_head", sa.String(length=40), nullable=True),
        sa.Column("rollback_seguro", sa.Boolean(), nullable=True),
        sa.Column("solicitado_por_id", sa.Integer(), nullable=True),
        sa.Column(
            "solicitado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("iniciado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duracao_seg", sa.Integer(), nullable=True),
        sa.Column("log", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["solicitado_por_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deploys_solicitado_em"), "deploys", ["solicitado_em"], unique=False)
    op.create_index(op.f("ix_deploys_status"), "deploys", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deploys_status"), table_name="deploys")
    op.drop_index(op.f("ix_deploys_solicitado_em"), table_name="deploys")
    op.drop_table("deploys")
    op.drop_table("ci_status_cache")
    # ### end Alembic commands ###
