"""imagem por variacao

Revision ID: de1bbd3b488c
Revises: ebe4f3cc404e
Create Date: 2026-06-24 14:59:25.440618

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de1bbd3b488c"
down_revision: str | None = "ebe4f3cc404e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "produto_variacoes", sa.Column("imagem_filename", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("produto_variacoes", "imagem_filename")
    # ### end Alembic commands ###
