"""schema inicial

Revision ID: ebe4f3cc404e
Revises:
Create Date: 2026-06-23 00:15:01.846740

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe4f3cc404e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensão de busca por similaridade (busca rápida no tablet/estoque).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # Sequence dedicada para numeração de pedido sem buracos (doc 03 §4).
    op.execute("CREATE SEQUENCE IF NOT EXISTS pedido_numero_seq START 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categorias_nome"), "categorias", ["nome"], unique=True)
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("cnpj_cpf", sa.String(length=20), nullable=True),
        sa.Column("telefone", sa.String(length=40), nullable=True),
        sa.Column("endereco", sa.Text(), nullable=True),
        sa.Column("condicao_pagto_padrao", sa.String(length=60), nullable=True),
        sa.Column("limite_credito", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_nome"), "clientes", ["nome"], unique=False)
    op.create_table(
        "fornecedores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("cnpj", sa.String(length=20), nullable=True),
        sa.Column("contato", sa.String(length=160), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fornecedores_nome"), "fornecedores", ["nome"], unique=False)
    op.create_table(
        "sync_outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entidade", sa.String(length=60), nullable=False),
        sa.Column("entidade_id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tentativas", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=180), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column("perfil", sa.String(length=20), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_perfil"), "usuarios", ["perfil"], unique=False)
    op.create_table(
        "auditoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("entidade", sa.String(length=60), nullable=False),
        sa.Column("entidade_id", sa.Integer(), nullable=True),
        sa.Column("acao", sa.String(length=40), nullable=False),
        sa.Column("antes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("depois", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auditoria_criado_em"), "auditoria", ["criado_em"], unique=False)
    op.create_index(op.f("ix_auditoria_entidade"), "auditoria", ["entidade"], unique=False)
    op.create_table(
        "inventarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(length=160), nullable=True),
        sa.Column(
            "status", sa.Enum("aberto", "aplicado", name="status_inventario"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("criado_por", sa.Integer(), nullable=False),
        sa.Column("aplicado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aplicado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aplicado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventarios_status"), "inventarios", ["status"], unique=False)
    op.create_table(
        "pedidos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("vendedor_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "rascunho",
                "confirmado",
                "separacao",
                "faturado",
                "entregue",
                "cancelado",
                name="status_pedido",
            ),
            nullable=False,
        ),
        sa.Column("desconto_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column(
            "origem", sa.Enum("local", "catalogo", "whatsapp", name="origem_pedido"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("faturado_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendedor_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pedidos_cliente_id"), "pedidos", ["cliente_id"], unique=False)
    op.create_index(op.f("ix_pedidos_criado_em"), "pedidos", ["criado_em"], unique=False)
    op.create_index(op.f("ix_pedidos_numero"), "pedidos", ["numero"], unique=True)
    op.create_index(op.f("ix_pedidos_status"), "pedidos", ["status"], unique=False)
    op.create_index(op.f("ix_pedidos_vendedor_id"), "pedidos", ["vendedor_id"], unique=False)
    op.create_table(
        "produtos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=60), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=True),
        sa.Column("unidades_por_caixa", sa.Integer(), nullable=True),
        sa.Column("localizacao", sa.String(length=255), nullable=True),
        sa.Column("preco_pouca_qtd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("preco_muita_qtd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("preco_promocional", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("qtd_corte_atacado", sa.Integer(), nullable=True),
        sa.Column("preco_custo", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("publicar_catalogo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_produtos_codigo"), "produtos", ["codigo"], unique=True)
    op.create_table(
        "contas_receber",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("parcela", sa.Integer(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vencimento", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("pendente", "pago", "atrasado", name="status_conta"), nullable=False
        ),
        sa.Column("forma_pagamento", sa.String(length=40), nullable=True),
        sa.Column("baixado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baixado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baixado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contas_receber_pedido_id"), "contas_receber", ["pedido_id"], unique=False
    )
    op.create_index(op.f("ix_contas_receber_status"), "contas_receber", ["status"], unique=False)
    op.create_index(
        op.f("ix_contas_receber_vencimento"), "contas_receber", ["vencimento"], unique=False
    )
    op.create_table(
        "produto_codigos_alt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.Column("codigo_alt", sa.String(length=60), nullable=False),
        sa.Column("fornecedor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fornecedor_id"],
            ["fornecedores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_produto_codigos_alt_codigo_alt"),
        "produto_codigos_alt",
        ["codigo_alt"],
        unique=False,
    )
    op.create_index(
        op.f("ix_produto_codigos_alt_produto_id"),
        "produto_codigos_alt",
        ["produto_id"],
        unique=False,
    )
    op.create_table(
        "produto_variacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.Column("cor", sa.String(length=80), nullable=False),
        sa.Column(
            "estoque_modo", sa.Enum("EXATO", "APROXIMADO", name="estoque_modo"), nullable=False
        ),
        sa.Column("estoque_fisico", sa.Integer(), nullable=False),
        sa.Column("estoque_reservado", sa.Integer(), nullable=False),
        sa.Column(
            "rotulo_aprox",
            sa.Enum("MUITO", "POUCO", "TEM", "ACABOU", name="rotulo_aprox"),
            nullable=True,
        ),
        sa.Column("estoque_minimo", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_produto_variacoes_cor"), "produto_variacoes", ["cor"], unique=False)
    op.create_index(
        op.f("ix_produto_variacoes_produto_id"), "produto_variacoes", ["produto_id"], unique=False
    )
    op.create_table(
        "inventario_itens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inventario_id", sa.Integer(), nullable=False),
        sa.Column("produto_variacao_id", sa.Integer(), nullable=False),
        sa.Column("qtd_sistema", sa.Integer(), nullable=False),
        sa.Column("qtd_contada", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inventario_id"],
            ["inventarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_variacao_id"],
            ["produto_variacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventario_itens_inventario_id"),
        "inventario_itens",
        ["inventario_id"],
        unique=False,
    )
    op.create_table(
        "movimentacoes_estoque",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_variacao_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("entrada", "saida", "ajuste", "reserva", "estorno", name="tipo_mov"),
            nullable=False,
        ),
        sa.Column("qtd", sa.Integer(), nullable=False),
        sa.Column(
            "origem",
            sa.Enum("pedido", "inventario", "importacao", "manual", name="origem_mov"),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("saldo_apos", sa.Integer(), nullable=False),
        sa.Column("motivo", sa.String(length=255), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["produto_variacao_id"],
            ["produto_variacoes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movimentacoes_estoque_criado_em"),
        "movimentacoes_estoque",
        ["criado_em"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimentacoes_estoque_produto_variacao_id"),
        "movimentacoes_estoque",
        ["produto_variacao_id"],
        unique=False,
    )
    op.create_table(
        "pedido_itens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("produto_variacao_id", sa.Integer(), nullable=False),
        sa.Column("qtd", sa.Integer(), nullable=False),
        sa.Column("qtd_caixas", sa.Integer(), nullable=True),
        sa.Column("preco_unit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("desconto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("separado", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_variacao_id"],
            ["produto_variacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pedido_itens_pedido_id"), "pedido_itens", ["pedido_id"], unique=False)
    op.create_index(
        op.f("ix_pedido_itens_produto_variacao_id"),
        "pedido_itens",
        ["produto_variacao_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Índices GIN trigram para busca por descrição e localização (tablet do estoque).
    op.execute(
        "CREATE INDEX ix_produtos_descricao_trgm ON produtos USING gin (descricao gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_produtos_localizacao_trgm ON produtos USING gin (localizacao gin_trgm_ops)"
    )
    # Índices compostos para relatórios de pedidos por vendedor/cliente e data.
    op.create_index("ix_pedidos_vendedor_criado", "pedidos", ["vendedor_id", "criado_em"])
    op.create_index("ix_pedidos_cliente_criado", "pedidos", ["cliente_id", "criado_em"])


def downgrade() -> None:
    op.drop_index("ix_pedidos_cliente_criado", table_name="pedidos")
    op.drop_index("ix_pedidos_vendedor_criado", table_name="pedidos")
    op.execute("DROP INDEX IF EXISTS ix_produtos_localizacao_trgm")
    op.execute("DROP INDEX IF EXISTS ix_produtos_descricao_trgm")
    op.execute("DROP SEQUENCE IF EXISTS pedido_numero_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pedido_itens_produto_variacao_id"), table_name="pedido_itens")
    op.drop_index(op.f("ix_pedido_itens_pedido_id"), table_name="pedido_itens")
    op.drop_table("pedido_itens")
    op.drop_index(
        op.f("ix_movimentacoes_estoque_produto_variacao_id"), table_name="movimentacoes_estoque"
    )
    op.drop_index(op.f("ix_movimentacoes_estoque_criado_em"), table_name="movimentacoes_estoque")
    op.drop_table("movimentacoes_estoque")
    op.drop_index(op.f("ix_inventario_itens_inventario_id"), table_name="inventario_itens")
    op.drop_table("inventario_itens")
    op.drop_index(op.f("ix_produto_variacoes_produto_id"), table_name="produto_variacoes")
    op.drop_index(op.f("ix_produto_variacoes_cor"), table_name="produto_variacoes")
    op.drop_table("produto_variacoes")
    op.drop_index(op.f("ix_produto_codigos_alt_produto_id"), table_name="produto_codigos_alt")
    op.drop_index(op.f("ix_produto_codigos_alt_codigo_alt"), table_name="produto_codigos_alt")
    op.drop_table("produto_codigos_alt")
    op.drop_index(op.f("ix_contas_receber_vencimento"), table_name="contas_receber")
    op.drop_index(op.f("ix_contas_receber_status"), table_name="contas_receber")
    op.drop_index(op.f("ix_contas_receber_pedido_id"), table_name="contas_receber")
    op.drop_table("contas_receber")
    op.drop_index(op.f("ix_produtos_codigo"), table_name="produtos")
    op.drop_table("produtos")
    op.drop_index(op.f("ix_pedidos_vendedor_id"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_status"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_numero"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_criado_em"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_cliente_id"), table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_index(op.f("ix_inventarios_status"), table_name="inventarios")
    op.drop_table("inventarios")
    op.drop_index(op.f("ix_auditoria_entidade"), table_name="auditoria")
    op.drop_index(op.f("ix_auditoria_criado_em"), table_name="auditoria")
    op.drop_table("auditoria")
    op.drop_index(op.f("ix_usuarios_perfil"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("sync_outbox")
    op.drop_index(op.f("ix_fornecedores_nome"), table_name="fornecedores")
    op.drop_table("fornecedores")
    op.drop_index(op.f("ix_clientes_nome"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(op.f("ix_categorias_nome"), table_name="categorias")
    op.drop_table("categorias")
    # ### end Alembic commands ###

    # Tipos ENUM não são removidos com as tabelas — dropar explicitamente.
    for tipo in (
        "estoque_modo",
        "rotulo_aprox",
        "tipo_mov",
        "origem_mov",
        "status_pedido",
        "origem_pedido",
        "status_conta",
        "status_inventario",
    ):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
